// Code generated by "stringer -type=FieldKind"; DO NOT EDIT.

package forms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldKindUnknown-0]
	_ = x[FieldKindID-1]
	_ = x[FieldKindTextInput-2]
	_ = x[FieldKindNumberInput-3]
	_ = x[FieldKindDateInput-4]
	_ = x[FieldKindSelect-5]
	_ = x[FieldKindCheckboxInput-6]
	_ = x[FieldKindTextarea-7]
	_ = x[FieldKindHiddenInput-8]
}

const _FieldKind_name = "FieldKindUnknownFieldKindIDFieldKindTextInputFieldKindNumberInputFieldKindDateInputFieldKindSelectFieldKindCheckboxInputFieldKindTextareaFieldKindHiddenInput"

var _FieldKind_index = [...]uint8{0, 16, 27, 45, 65, 83, 98, 120, 137, 157}

func (i FieldKind) String() string {
	if i >= FieldKind(len(_FieldKind_index)-1) {
		return "FieldKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldKind_name[_FieldKind_index[i]:_FieldKind_index[i+1]]
}
