services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "core"
    ports:
      - "5432:5432"
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    ports:
      - "4180:4180"
    restart: on-failure
    depends_on:
      - oidc
    command:
      - /bin/oauth2-proxy
      - --cookie-secret=5bbca15ead8e545ad4ad262b60faf127
      - --whitelist-domain=localhost:10000
      - --http-address=0.0.0.0:4180
      - --client-id=foo
      - --client-secret=bar
      - --email-domain=*
      - --upstream=static://200
      - --provider=oidc
      - --provider-display-name="Oidc"
      - --client-id=foo
      - --client-secret=bar
      - --scope=openid email profile groups
      - --redirect-url=https://localhost:10000/oauth2/callback
      - --cookie-secure=true
      - --cookie-samesite=lax
      - --cookie-csrf-per-request=true
      - --cookie-csrf-expire=5m
      - --cookie-refresh=5m
      - --email-domain=*
      - --oidc-issuer-url=https://localhost:10000
      - --insecure-oidc-skip-issuer-verification=true
      - --skip-oidc-discovery=true
      - --skip-provider-button=true
      - --oidc-jwks-url=http://oidc:9000/certs
      - --login-url=https://localhost:10000/auth
      - --redeem-url=http://oidc:9000/token
      - --profile-url=http://oidc:9000/me
      - --pass-access-token=true
      - --pass-authorization-header=true
      - --reverse-proxy=true
      - --set-authorization-header=true
      - --set-xauthrequest=true
  oidc:
    image: qlik/simple-oidc-provider
    volumes:
      - ./oidc-config.json:/etc/config.json
      - ./oidc-users.json:/etc/users.json
    environment:
      REDIRECTS: https://oauth2.core.dev:10000/oauth2/callback
      CONFIG_FILE: /etc/config.json
      USERS_FILE: /etc/users.json
    healthcheck:
      test: curl http://localhost/.well-known/openid-configuration
    ports:
      - "9000:9000"
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    depends_on:
      - oauth2-proxy
      - oidc
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./certs/tls.key:/etc/envoy/certs/tls.key
      - ./certs/tls.crt:/etc/envoy/certs/tls.crt
    extra_hosts:
      - "host.docker.internal:host-gateway"
  azure_blob_storage:
    image: mcr.microsoft.com/azure-storage/azurite
    command: 'azurite -l /data --blobHost 0.0.0.0 --blobPort 11000 --queueHost 0.0.0.0 --queuePort 11001 --tableHost 0.0.0.0 --tablePort 11002'
    ports:
      - '11000:11000'
      - '11001:11001'
      - '11002:11002'
