DROP table individuals;
CREATE EXTENSION if not exists "uuid-ossp";
CREATE TABLE individual_registration
(
    address                           varchar(512)             NOT NULL,
    birth_date                        date                     NULL,
    cognitive_disability_level        int                      NOT NULL,
    collection_administrative_area_1  varchar(128)             NOT NULL,
    collection_administrative_area_2  varchar(128)             NOT NULL,
    collection_administrative_area_3  varchar(128)             NOT NULL,
    collection_agent_name             varchar(64)              NOT NULL,
    collection_agent_title            varchar(64)              NOT NULL,
    collection_time                   timestamp with time zone NOT NULL,
    communication_disability_level    int                      NOT NULL,
    community_id                      varchar(64)              NOT NULL,
    country_id                        uuid                     NOT NULL,
    created_at                        timestamp with time zone NOT NULL,
    displacement_status               varchar(64)              NOT NULL,
    email                             varchar(255)             NOT NULL,
    full_name                         varchar(255)             NOT NULL,
    gender                            varchar(32)              NOT NULL,
    has_cognitive_disability          boolean                  NOT NULL,
    has_communication_disability      boolean                  NOT NULL,
    has_consented_to_rgpd             boolean                  NOT NULL,
    has_consented_to_referral         boolean                  NOT NULL,
    has_hearing_disability            boolean                  NOT NULL,
    has_mobility_disability           boolean                  NOT NULL,
    has_selfcare_disability           boolean                  NOT NULL,
    has_vision_disability             boolean                  NOT NULL,
    hearing_disability_level          int                      NOT NULL,
    household_id                      varchar(64)              NOT NULL,
    id                                uuid                     NOT NULL,
    identification_type_1             varchar(64)              NOT NULL,
    identification_type_explanation_1 varchar(255)             NOT NULL,
    identification_number_1           varchar(64)              NOT NULL,
    identification_type_2             varchar(64)              NOT NULL,
    identification_type_explanation_2 varchar(255)             NOT NULL,
    identification_number_2           varchar(64)              NOT NULL,
    identification_type_3             varchar(64)              NOT NULL,
    identification_type_explanation_3 varchar(255)             NOT NULL,
    identification_number_3           varchar(64)              NOT NULL,
    identification_context            varchar(64)              NOT NULL,
    internal_id                       varchar(64)              NOT NULL,
    is_birthdate_approximate          boolean                  NOT NULL,
    is_head_of_community              boolean                  NOT NULL,
    is_head_of_household              boolean                  NOT NULL,
    is_minor                          boolean                  NOT NULL,
    mobility_disability_level         int                      NOT NULL,
    nationality_1                     varchar(64)              NOT NULL,
    nationality_2                     varchar(64)              NOT NULL,
    normalized_phone_number           varchar(64)              NOT NULL,
    phone_number                      varchar(64)              NOT NULL,
    preferred_contact_method          varchar(64)              NOT NULL,
    preferred_contact_method_comments varchar(255)             NOT NULL,
    preferred_name                    varchar(255)             NOT NULL,
    preferred_communication_language  varchar(64)              NOT NULL,
    prefers_to_remain_anonymous       boolean                  NOT NULL,
    presents_protection_concerns      boolean                  NOT NULL,
    selfcare_disability_level         int                      NOT NULL,
    spoken_language_1                 varchar(64)              NOT NULL,
    spoken_language_2                 varchar(64)              NOT NULL,
    spoken_language_3                 varchar(64)              NOT NULL,
    updated_at                        timestamp with time zone NOT NULL,
    vision_disability_level           int                      NOT NULL
);

