ALTER TABLE individual_registrations
    ADD COLUMN IF NOT EXISTS service_type_1             VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_1                  VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_1      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_1         VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_1            VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_1     VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_1       VARCHAR(255) NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_2             VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_2                  VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_2      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_2         VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_2            VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_2     VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_2       VARCHAR(255) NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_3             VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_3                  VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_3      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_3         VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_3            VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_3     VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_3       VARCHAR(255) NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_4             VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_4                  VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_4      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_4         VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_4            VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_4     VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_4       VARCHAR(255) NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_5             VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_5                  VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_5      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_5         VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_5            VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_5     VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_5       VARCHAR(255) NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_6             VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_6                  VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_6      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_6         VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_6            VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_6     VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_6       VARCHAR(255) NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_7             VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_7                  VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_7      VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_7         VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_7            VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_7     VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_7       VARCHAR(255) NOT NULL DEFAULT '';

