ALTER TABLE individual_registrations
    ADD COLUMN IF NOT EXISTS service_type_1             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_1                  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_1      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_1         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_1            TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_1     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_1       TEXT NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_2             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_2                  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_2      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_2         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_2            TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_2     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_2       TEXT NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_3             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_3                  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_3      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_3         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_3            TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_3     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_3       TEXT NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_4             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_4                  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_4      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_4         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_4            TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_4     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_4       TEXT NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_5             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_5                  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_5      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_5         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_5            TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_5     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_5       TEXT NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_6             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_6                  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_6      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_6         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_6            TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_6     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_6       TEXT NOT NULL DEFAULT '',

    ADD COLUMN IF NOT EXISTS service_type_7             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_7                  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_sub_service_7      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_location_7         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_donor_7            TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_project_name_7     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_agent_name_7       TEXT NOT NULL DEFAULT '',

