// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: forms_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId string `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
}

func (x *GetFormRequest) Reset() {
	*x = GetFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormRequest) ProtoMessage() {}

func (x *GetFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormRequest.ProtoReflect.Descriptor instead.
func (*GetFormRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetFormRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

type GetFormResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *Form `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *GetFormResponse) Reset() {
	*x = GetFormResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormResponse) ProtoMessage() {}

func (x *GetFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormResponse.ProtoReflect.Descriptor instead.
func (*GetFormResponse) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type CreateFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *Form `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *CreateFormRequest) Reset() {
	*x = CreateFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormRequest) ProtoMessage() {}

func (x *CreateFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormRequest.ProtoReflect.Descriptor instead.
func (*CreateFormRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFormRequest) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type CreateFormResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *Form `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *CreateFormResponse) Reset() {
	*x = CreateFormResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormResponse) ProtoMessage() {}

func (x *CreateFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormResponse.ProtoReflect.Descriptor instead.
func (*CreateFormResponse) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type UpdateFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *Form `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *UpdateFormRequest) Reset() {
	*x = UpdateFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormRequest) ProtoMessage() {}

func (x *UpdateFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFormRequest) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type UpdateFormResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *Form `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *UpdateFormResponse) Reset() {
	*x = UpdateFormResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormResponse) ProtoMessage() {}

func (x *UpdateFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormResponse.ProtoReflect.Descriptor instead.
func (*UpdateFormResponse) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type DeleteFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId string `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
}

func (x *DeleteFormRequest) Reset() {
	*x = DeleteFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormRequest) ProtoMessage() {}

func (x *DeleteFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormRequest.ProtoReflect.Descriptor instead.
func (*DeleteFormRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFormRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

type FieldValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{7}
}

func (x *FieldValue) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *FieldValue) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordId    string        `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	FormId      string        `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	FieldValues []*FieldValue `protobuf:"bytes,3,rep,name=field_values,json=fieldValues,proto3" json:"field_values,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{8}
}

func (x *Record) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Record) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *Record) GetFieldValues() []*FieldValue {
	if x != nil {
		return x.FieldValues
	}
	return nil
}

type GetRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId   string `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	RecordId string `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecordRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *GetRecordRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type GetRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *UpdateRecordResponse) Reset() {
	*x = UpdateRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordResponse) ProtoMessage() {}

func (x *UpdateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordResponse) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId   string `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	RecordId string `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRecordRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *DeleteRecordRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type SearchRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId    string           `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Predicate *RecordPredicate `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
}

func (x *SearchRecordsRequest) Reset() {
	*x = SearchRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRecordsRequest) ProtoMessage() {}

func (x *SearchRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRecordsRequest.ProtoReflect.Descriptor instead.
func (*SearchRecordsRequest) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{14}
}

func (x *SearchRecordsRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *SearchRecordsRequest) GetPredicate() *RecordPredicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

type ListPagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *ListPagination) Reset() {
	*x = ListPagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagination) ProtoMessage() {}

func (x *ListPagination) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagination.ProtoReflect.Descriptor instead.
func (*ListPagination) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListPagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPagination) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type SearchRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *ListPagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Records    []*Record       `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *SearchRecordsResponse) Reset() {
	*x = SearchRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRecordsResponse) ProtoMessage() {}

func (x *SearchRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forms_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRecordsResponse.ProtoReflect.Descriptor instead.
func (*SearchRecordsResponse) Descriptor() ([]byte, []int) {
	return file_forms_service_proto_rawDescGZIP(), []int{16}
}

func (x *SearchRecordsResponse) GetPagination() *ListPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_forms_service_proto protoreflect.FileDescriptor

var file_forms_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x1a, 0x0b, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6f,
	0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72,
	0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46, 0x6f, 0x72, 0x6d,
	0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x3f, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x66,
	0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e,
	0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46, 0x6f, 0x72,
	0x6d, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x40, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x6f,
	0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x3f, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e,
	0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x46, 0x6f, 0x72, 0x6d, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x40, 0x0a, 0x12, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x2c, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x0a, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x7f, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x49,
	0x64, 0x12, 0x3f, 0x0a, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x48, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x22, 0x47, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x2e,
	0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x48, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x4b, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66,
	0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x09, 0x70, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x4c, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x32, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x32, 0xe2, 0x02, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x20,
	0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x6f, 0x72, 0x6d, 0x12, 0x23, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72,
	0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x59, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x23,
	0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x23, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e,
	0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32, 0xfd, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6e, 0x6f,
	0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x25, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e,
	0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x25, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x26, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forms_service_proto_rawDescOnce sync.Once
	file_forms_service_proto_rawDescData = file_forms_service_proto_rawDesc
)

func file_forms_service_proto_rawDescGZIP() []byte {
	file_forms_service_proto_rawDescOnce.Do(func() {
		file_forms_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_forms_service_proto_rawDescData)
	})
	return file_forms_service_proto_rawDescData
}

var file_forms_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_forms_service_proto_goTypes = []interface{}{
	(*GetFormRequest)(nil),        // 0: no.nrc.core.form.GetFormRequest
	(*GetFormResponse)(nil),       // 1: no.nrc.core.form.GetFormResponse
	(*CreateFormRequest)(nil),     // 2: no.nrc.core.form.CreateFormRequest
	(*CreateFormResponse)(nil),    // 3: no.nrc.core.form.CreateFormResponse
	(*UpdateFormRequest)(nil),     // 4: no.nrc.core.form.UpdateFormRequest
	(*UpdateFormResponse)(nil),    // 5: no.nrc.core.form.UpdateFormResponse
	(*DeleteFormRequest)(nil),     // 6: no.nrc.core.form.DeleteFormRequest
	(*FieldValue)(nil),            // 7: no.nrc.core.form.FieldValue
	(*Record)(nil),                // 8: no.nrc.core.form.Record
	(*GetRecordRequest)(nil),      // 9: no.nrc.core.form.GetRecordRequest
	(*GetRecordResponse)(nil),     // 10: no.nrc.core.form.GetRecordResponse
	(*UpdateRecordRequest)(nil),   // 11: no.nrc.core.form.UpdateRecordRequest
	(*UpdateRecordResponse)(nil),  // 12: no.nrc.core.form.UpdateRecordResponse
	(*DeleteRecordRequest)(nil),   // 13: no.nrc.core.form.DeleteRecordRequest
	(*SearchRecordsRequest)(nil),  // 14: no.nrc.core.form.SearchRecordsRequest
	(*ListPagination)(nil),        // 15: no.nrc.core.form.ListPagination
	(*SearchRecordsResponse)(nil), // 16: no.nrc.core.form.SearchRecordsResponse
	(*Form)(nil),                  // 17: no.nrc.core.form.Form
	(*structpb.Value)(nil),        // 18: google.protobuf.Value
	(*RecordPredicate)(nil),       // 19: no.nrc.core.form.RecordPredicate
	(*emptypb.Empty)(nil),         // 20: google.protobuf.Empty
}
var file_forms_service_proto_depIdxs = []int32{
	17, // 0: no.nrc.core.form.GetFormResponse.form:type_name -> no.nrc.core.form.Form
	17, // 1: no.nrc.core.form.CreateFormRequest.form:type_name -> no.nrc.core.form.Form
	17, // 2: no.nrc.core.form.CreateFormResponse.form:type_name -> no.nrc.core.form.Form
	17, // 3: no.nrc.core.form.UpdateFormRequest.form:type_name -> no.nrc.core.form.Form
	17, // 4: no.nrc.core.form.UpdateFormResponse.form:type_name -> no.nrc.core.form.Form
	18, // 5: no.nrc.core.form.FieldValue.value:type_name -> google.protobuf.Value
	7,  // 6: no.nrc.core.form.Record.field_values:type_name -> no.nrc.core.form.FieldValue
	8,  // 7: no.nrc.core.form.GetRecordResponse.record:type_name -> no.nrc.core.form.Record
	8,  // 8: no.nrc.core.form.UpdateRecordRequest.record:type_name -> no.nrc.core.form.Record
	8,  // 9: no.nrc.core.form.UpdateRecordResponse.record:type_name -> no.nrc.core.form.Record
	19, // 10: no.nrc.core.form.SearchRecordsRequest.predicate:type_name -> no.nrc.core.form.RecordPredicate
	15, // 11: no.nrc.core.form.SearchRecordsResponse.pagination:type_name -> no.nrc.core.form.ListPagination
	8,  // 12: no.nrc.core.form.SearchRecordsResponse.records:type_name -> no.nrc.core.form.Record
	0,  // 13: no.nrc.core.form.FormService.GetForm:input_type -> no.nrc.core.form.GetFormRequest
	2,  // 14: no.nrc.core.form.FormService.CreateForm:input_type -> no.nrc.core.form.CreateFormRequest
	4,  // 15: no.nrc.core.form.FormService.UpdateForm:input_type -> no.nrc.core.form.UpdateFormRequest
	6,  // 16: no.nrc.core.form.FormService.DeleteForm:input_type -> no.nrc.core.form.DeleteFormRequest
	9,  // 17: no.nrc.core.form.RecordService.GetRecord:input_type -> no.nrc.core.form.GetRecordRequest
	11, // 18: no.nrc.core.form.RecordService.UpdateRecord:input_type -> no.nrc.core.form.UpdateRecordRequest
	13, // 19: no.nrc.core.form.RecordService.DeleteRecord:input_type -> no.nrc.core.form.DeleteRecordRequest
	14, // 20: no.nrc.core.form.RecordService.SearchRecords:input_type -> no.nrc.core.form.SearchRecordsRequest
	1,  // 21: no.nrc.core.form.FormService.GetForm:output_type -> no.nrc.core.form.GetFormResponse
	3,  // 22: no.nrc.core.form.FormService.CreateForm:output_type -> no.nrc.core.form.CreateFormResponse
	5,  // 23: no.nrc.core.form.FormService.UpdateForm:output_type -> no.nrc.core.form.UpdateFormResponse
	20, // 24: no.nrc.core.form.FormService.DeleteForm:output_type -> google.protobuf.Empty
	10, // 25: no.nrc.core.form.RecordService.GetRecord:output_type -> no.nrc.core.form.GetRecordResponse
	12, // 26: no.nrc.core.form.RecordService.UpdateRecord:output_type -> no.nrc.core.form.UpdateRecordResponse
	20, // 27: no.nrc.core.form.RecordService.DeleteRecord:output_type -> google.protobuf.Empty
	16, // 28: no.nrc.core.form.RecordService.SearchRecords:output_type -> no.nrc.core.form.SearchRecordsResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_forms_service_proto_init() }
func file_forms_service_proto_init() {
	if File_forms_service_proto != nil {
		return
	}
	file_forms_proto_init()
	file_predicates_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_forms_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFormResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFormResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFormResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forms_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forms_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_forms_service_proto_goTypes,
		DependencyIndexes: file_forms_service_proto_depIdxs,
		MessageInfos:      file_forms_service_proto_msgTypes,
	}.Build()
	File_forms_service_proto = out.File
	file_forms_service_proto_rawDesc = nil
	file_forms_service_proto_goTypes = nil
	file_forms_service_proto_depIdxs = nil
}
