// This is a sample package that defines
// message types for various types of predicates.
//
// Could be useful to represent database query conditions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: predicates.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Predicate *anypb.Any `protobuf:"bytes,1,opt,name=predicate,proto3" json:"predicate,omitempty"`
}

func (x *RecordPredicate) Reset() {
	*x = RecordPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPredicate) ProtoMessage() {}

func (x *RecordPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPredicate.ProtoReflect.Descriptor instead.
func (*RecordPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{0}
}

func (x *RecordPredicate) GetPredicate() *anypb.Any {
	if x != nil {
		return x.Predicate
	}
	return nil
}

type AllOfPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Predicates []*RecordPredicate `protobuf:"bytes,1,rep,name=predicates,proto3" json:"predicates,omitempty"`
}

func (x *AllOfPredicate) Reset() {
	*x = AllOfPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllOfPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOfPredicate) ProtoMessage() {}

func (x *AllOfPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOfPredicate.ProtoReflect.Descriptor instead.
func (*AllOfPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{1}
}

func (x *AllOfPredicate) GetPredicates() []*RecordPredicate {
	if x != nil {
		return x.Predicates
	}
	return nil
}

type AnyOfPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Predicates []*RecordPredicate `protobuf:"bytes,1,rep,name=predicates,proto3" json:"predicates,omitempty"`
}

func (x *AnyOfPredicate) Reset() {
	*x = AnyOfPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnyOfPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyOfPredicate) ProtoMessage() {}

func (x *AnyOfPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyOfPredicate.ProtoReflect.Descriptor instead.
func (*AnyOfPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{2}
}

func (x *AnyOfPredicate) GetPredicates() []*RecordPredicate {
	if x != nil {
		return x.Predicates
	}
	return nil
}

type NotPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Predicate *RecordPredicate `protobuf:"bytes,1,opt,name=predicate,proto3" json:"predicate,omitempty"`
}

func (x *NotPredicate) Reset() {
	*x = NotPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotPredicate) ProtoMessage() {}

func (x *NotPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotPredicate.ProtoReflect.Descriptor instead.
func (*NotPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{3}
}

func (x *NotPredicate) GetPredicate() *RecordPredicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

type EqualityPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EqualityPredicate) Reset() {
	*x = EqualityPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EqualityPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqualityPredicate) ProtoMessage() {}

func (x *EqualityPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqualityPredicate.ProtoReflect.Descriptor instead.
func (*EqualityPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{4}
}

func (x *EqualityPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *EqualityPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type InequalityPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *InequalityPredicate) Reset() {
	*x = InequalityPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InequalityPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InequalityPredicate) ProtoMessage() {}

func (x *InequalityPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InequalityPredicate.ProtoReflect.Descriptor instead.
func (*InequalityPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{5}
}

func (x *InequalityPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *InequalityPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContainsPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ContainsPredicate) Reset() {
	*x = ContainsPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainsPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsPredicate) ProtoMessage() {}

func (x *ContainsPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsPredicate.ProtoReflect.Descriptor instead.
func (*ContainsPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{6}
}

func (x *ContainsPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *ContainsPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type StartsWithPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StartsWithPredicate) Reset() {
	*x = StartsWithPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartsWithPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartsWithPredicate) ProtoMessage() {}

func (x *StartsWithPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartsWithPredicate.ProtoReflect.Descriptor instead.
func (*StartsWithPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{7}
}

func (x *StartsWithPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *StartsWithPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type EndsWithPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EndsWithPredicate) Reset() {
	*x = EndsWithPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndsWithPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndsWithPredicate) ProtoMessage() {}

func (x *EndsWithPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndsWithPredicate.ProtoReflect.Descriptor instead.
func (*EndsWithPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{8}
}

func (x *EndsWithPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *EndsWithPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type GreaterThanPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GreaterThanPredicate) Reset() {
	*x = GreaterThanPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreaterThanPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreaterThanPredicate) ProtoMessage() {}

func (x *GreaterThanPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreaterThanPredicate.ProtoReflect.Descriptor instead.
func (*GreaterThanPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{9}
}

func (x *GreaterThanPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *GreaterThanPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type GreaterThanOrEqualPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GreaterThanOrEqualPredicate) Reset() {
	*x = GreaterThanOrEqualPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreaterThanOrEqualPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreaterThanOrEqualPredicate) ProtoMessage() {}

func (x *GreaterThanOrEqualPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreaterThanOrEqualPredicate.ProtoReflect.Descriptor instead.
func (*GreaterThanOrEqualPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{10}
}

func (x *GreaterThanOrEqualPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *GreaterThanOrEqualPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type LessThanPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LessThanPredicate) Reset() {
	*x = LessThanPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessThanPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessThanPredicate) ProtoMessage() {}

func (x *LessThanPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessThanPredicate.ProtoReflect.Descriptor instead.
func (*LessThanPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{11}
}

func (x *LessThanPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *LessThanPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type LessThanOrEqualPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LessThanOrEqualPredicate) Reset() {
	*x = LessThanOrEqualPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessThanOrEqualPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessThanOrEqualPredicate) ProtoMessage() {}

func (x *LessThanOrEqualPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessThanOrEqualPredicate.ProtoReflect.Descriptor instead.
func (*LessThanOrEqualPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{12}
}

func (x *LessThanOrEqualPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *LessThanOrEqualPredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type LikePredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Value   *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LikePredicate) Reset() {
	*x = LikePredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikePredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePredicate) ProtoMessage() {}

func (x *LikePredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePredicate.ProtoReflect.Descriptor instead.
func (*LikePredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{13}
}

func (x *LikePredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *LikePredicate) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type RangePredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string          `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Min     *structpb.Value `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     *structpb.Value `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *RangePredicate) Reset() {
	*x = RangePredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangePredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangePredicate) ProtoMessage() {}

func (x *RangePredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangePredicate.ProtoReflect.Descriptor instead.
func (*RangePredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{14}
}

func (x *RangePredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *RangePredicate) GetMin() *structpb.Value {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *RangePredicate) GetMax() *structpb.Value {
	if x != nil {
		return x.Max
	}
	return nil
}

type InPredicate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId string            `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Values  []*structpb.Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *InPredicate) Reset() {
	*x = InPredicate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predicates_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InPredicate) ProtoMessage() {}

func (x *InPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_predicates_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InPredicate.ProtoReflect.Descriptor instead.
func (*InPredicate) Descriptor() ([]byte, []int) {
	return file_predicates_proto_rawDescGZIP(), []int{15}
}

func (x *InPredicate) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *InPredicate) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_predicates_proto protoreflect.FileDescriptor

var file_predicates_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x66, 0x6f, 0x72, 0x6d, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a,
	0x0f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x32, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x4f, 0x66, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x6f, 0x2e,
	0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x22, 0x53, 0x0a, 0x0e, 0x41, 0x6e, 0x79,
	0x4f, 0x66, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x22, 0x4f,
	0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x3f,
	0x0a, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6e, 0x6f, 0x2e, 0x6e, 0x72, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x52, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22,
	0x5c, 0x0a, 0x11, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5e, 0x0a,
	0x13, 0x49, 0x6e, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5c, 0x0a,
	0x11, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5e, 0x0a, 0x13, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5c, 0x0a, 0x11, 0x45,
	0x6e, 0x64, 0x73, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5f, 0x0a, 0x14, 0x47, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x66, 0x0a, 0x1b, 0x47, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x4f, 0x72, 0x45, 0x71, 0x75, 0x61, 0x6c,
	0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x5c, 0x0a, 0x11, 0x4c, 0x65, 0x73, 0x73, 0x54, 0x68, 0x61, 0x6e, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x63, 0x0a, 0x18, 0x4c, 0x65, 0x73, 0x73, 0x54, 0x68, 0x61, 0x6e, 0x4f, 0x72, 0x45, 0x71,
	0x75, 0x61, 0x6c, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x58, 0x0a, 0x0d, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x7f, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x22, 0x58, 0x0a, 0x0b, 0x49, 0x6e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_predicates_proto_rawDescOnce sync.Once
	file_predicates_proto_rawDescData = file_predicates_proto_rawDesc
)

func file_predicates_proto_rawDescGZIP() []byte {
	file_predicates_proto_rawDescOnce.Do(func() {
		file_predicates_proto_rawDescData = protoimpl.X.CompressGZIP(file_predicates_proto_rawDescData)
	})
	return file_predicates_proto_rawDescData
}

var file_predicates_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_predicates_proto_goTypes = []interface{}{
	(*RecordPredicate)(nil),             // 0: no.nrc.core.form.RecordPredicate
	(*AllOfPredicate)(nil),              // 1: no.nrc.core.form.AllOfPredicate
	(*AnyOfPredicate)(nil),              // 2: no.nrc.core.form.AnyOfPredicate
	(*NotPredicate)(nil),                // 3: no.nrc.core.form.NotPredicate
	(*EqualityPredicate)(nil),           // 4: no.nrc.core.form.EqualityPredicate
	(*InequalityPredicate)(nil),         // 5: no.nrc.core.form.InequalityPredicate
	(*ContainsPredicate)(nil),           // 6: no.nrc.core.form.ContainsPredicate
	(*StartsWithPredicate)(nil),         // 7: no.nrc.core.form.StartsWithPredicate
	(*EndsWithPredicate)(nil),           // 8: no.nrc.core.form.EndsWithPredicate
	(*GreaterThanPredicate)(nil),        // 9: no.nrc.core.form.GreaterThanPredicate
	(*GreaterThanOrEqualPredicate)(nil), // 10: no.nrc.core.form.GreaterThanOrEqualPredicate
	(*LessThanPredicate)(nil),           // 11: no.nrc.core.form.LessThanPredicate
	(*LessThanOrEqualPredicate)(nil),    // 12: no.nrc.core.form.LessThanOrEqualPredicate
	(*LikePredicate)(nil),               // 13: no.nrc.core.form.LikePredicate
	(*RangePredicate)(nil),              // 14: no.nrc.core.form.RangePredicate
	(*InPredicate)(nil),                 // 15: no.nrc.core.form.InPredicate
	(*anypb.Any)(nil),                   // 16: google.protobuf.Any
	(*structpb.Value)(nil),              // 17: google.protobuf.Value
}
var file_predicates_proto_depIdxs = []int32{
	16, // 0: no.nrc.core.form.RecordPredicate.predicate:type_name -> google.protobuf.Any
	0,  // 1: no.nrc.core.form.AllOfPredicate.predicates:type_name -> no.nrc.core.form.RecordPredicate
	0,  // 2: no.nrc.core.form.AnyOfPredicate.predicates:type_name -> no.nrc.core.form.RecordPredicate
	0,  // 3: no.nrc.core.form.NotPredicate.predicate:type_name -> no.nrc.core.form.RecordPredicate
	17, // 4: no.nrc.core.form.EqualityPredicate.value:type_name -> google.protobuf.Value
	17, // 5: no.nrc.core.form.InequalityPredicate.value:type_name -> google.protobuf.Value
	17, // 6: no.nrc.core.form.ContainsPredicate.value:type_name -> google.protobuf.Value
	17, // 7: no.nrc.core.form.StartsWithPredicate.value:type_name -> google.protobuf.Value
	17, // 8: no.nrc.core.form.EndsWithPredicate.value:type_name -> google.protobuf.Value
	17, // 9: no.nrc.core.form.GreaterThanPredicate.value:type_name -> google.protobuf.Value
	17, // 10: no.nrc.core.form.GreaterThanOrEqualPredicate.value:type_name -> google.protobuf.Value
	17, // 11: no.nrc.core.form.LessThanPredicate.value:type_name -> google.protobuf.Value
	17, // 12: no.nrc.core.form.LessThanOrEqualPredicate.value:type_name -> google.protobuf.Value
	17, // 13: no.nrc.core.form.LikePredicate.value:type_name -> google.protobuf.Value
	17, // 14: no.nrc.core.form.RangePredicate.min:type_name -> google.protobuf.Value
	17, // 15: no.nrc.core.form.RangePredicate.max:type_name -> google.protobuf.Value
	17, // 16: no.nrc.core.form.InPredicate.values:type_name -> google.protobuf.Value
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_predicates_proto_init() }
func file_predicates_proto_init() {
	if File_predicates_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_predicates_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllOfPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnyOfPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EqualityPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InequalityPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainsPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartsWithPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndsWithPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreaterThanPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreaterThanOrEqualPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LessThanPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LessThanOrEqualPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikePredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangePredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predicates_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InPredicate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_predicates_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_predicates_proto_goTypes,
		DependencyIndexes: file_predicates_proto_depIdxs,
		MessageInfos:      file_predicates_proto_msgTypes,
	}.Build()
	File_predicates_proto = out.File
	file_predicates_proto_rawDesc = nil
	file_predicates_proto_goTypes = nil
	file_predicates_proto_depIdxs = nil
}
