package handlers

const (
	formParamIndividualAddress                    = "Address"
	formParamIndividualBirthDate                  = "BirthDate"
	formParamIndividualCountry                    = "Country"
	formParamIndividualDisplacementStatus         = "DisplacementStatus"
	formParamIndividualEmail                      = "Email"
	formParamIndividualFullName                   = "FullName"
	formParamIndividualGender                     = "Gender"
	formParamIndividualIsMinor                    = "IsMinor"
	formParamIndividualMentalImpairment           = "MentalImpairment"
	formParamIndividualPhoneNumber                = "PhoneNumber"
	formParamIndividualPhysicalImpairment         = "PhysicalImpairment"
	formParamIndividualPreferredName              = "PreferredName"
	formParamIndividualPresentsProtectionConcerns = "PresentsProtectionConcerns"
	formParamIndividualSensoryImpairment          = "SensoryImpairment"

	formParamGetIndividualsEmail               = "email"
	formParamGetIndividualsName                = "name"
	formParamGetIndividualsPhoneNumber         = "phone_number"
	formParamsGetIndividualsAddress            = "address"
	formParamsGetIndividualsGender             = "gender"
	formParamsGetIndividualsIsMinor            = "is_minor"
	formParamsGetIndividualsProtectionConcerns = "presents_protection_concerns"
	formParamsGetIndividualsAgeFrom            = "age_from"
	formParamsGetIndividualsAgeTo              = "age_to"
	formParamGetIndividualsCountryID           = "country_id"
	formParamsGetIndividualsDisplacementStatus = "displacement_status"

	fileHeaderIndividualID                         = "id"
	fileHeaderIndividualAddress                    = "address"
	fileHeaderIndividualBirthDate                  = "birth_date"
	fileHeaderIndividualCountryID                  = "country_id"
	fileHeaderIndividualDisplacementStatus         = "displacement_status"
	fileHeaderIndividualEmail                      = "email"
	fileHeaderIndividualFullName                   = "full_name"
	fileHeaderIndividualGender                     = "gender"
	fileHeaderIndividualIsMinor                    = "is_minor"
	fileHeaderIndividualMentalImpairment           = "mental_impairment"
	fileHeaderIndividualPhoneNumber                = "phone_number"
	fileHeaderIndividualPhysicalImpairment         = "physical_impairment"
	fileHeaderIndividualPreferredName              = "preferred_name"
	fileHeaderIndividualPresentsProtectionConcerns = "presents_protection_concerns"
	fileHeaderIndividualSensoryImpairment          = "sensory_impairment"
)
