package handlers

const (
	formParamIndividualAddress                    = "Address"
	formParamIndividualBirthDate                  = "BirthDate"
	formParamIndividualCountry                    = "Country"
	formParamIndividualDisplacementStatus         = "DisplacementStatus"
	formParamIndividualEmail                      = "Email"
	formParamIndividualFullName                   = "FullName"
	formParamIndividualGender                     = "Gender"
	formParamIndividualIsMinor                    = "IsMinor"
	formParamIndividualMentalImpairment           = "MentalImpairment"
	formParamIndividualPhoneNumber                = "PhoneNumber"
	formParamIndividualPhysicalImpairment         = "PhysicalImpairment"
	formParamIndividualPreferredName              = "PreferredName"
	formParamIndividualPresentsProtectionConcerns = "PresentsProtectionConcerns"
	formParamIndividualSensoryImpairment          = "SensoryImpairment"

	formParamGetIndividualsEmail               = "email"
	formParamGetIndividualsName                = "name"
	formParamGetIndividualsPhoneNumber         = "phone_number"
	formParamsGetIndividualsAddress            = "address"
	formParamsGetIndividualsGender             = "gender"
	formParamsGetIndividualsIsMinor            = "is_minor"
	formParamsGetIndividualsProtectionConcerns = "presents_protection_concerns"
	formParamsGetIndividualsAgeFrom            = "age_from"
	formParamsGetIndividualsAgeTo              = "age_to"
	formParamGetIndividualsCountryID           = "country_id"
	formParamsGetIndividualsDisplacementStatus = "displacement_status"

	csvHeaderIndividualID                         = "id"
	csvHeaderIndividualAddress                    = "address"
	csvHeaderIndividualBirthDate                  = "birth_date"
	csvHeaderIndividualCountryID                  = "country_id"
	csvHeaderIndividualDisplacementStatus         = "displacement_status"
	csvHeaderIndividualEmail                      = "email"
	csvHeaderIndividualFullName                   = "full_name"
	csvHeaderIndividualGender                     = "gender"
	csvHeaderIndividualIsMinor                    = "is_minor"
	csvHeaderIndividualMentalImpairment           = "mental_impairment"
	csvHeaderIndividualPhoneNumber                = "phone_number"
	csvHeaderIndividualPhysicalImpairment         = "physical_impairment"
	csvHeaderIndividualPreferredName              = "preferred_name"
	csvHeaderIndividualPresentsProtectionConcerns = "presents_protection_concerns"
	csvHeaderIndividualSensoryImpairment          = "sensory_impairment"
)
