package constants

const (
	FormParamIndividualAddress                    = "Address"
	FormParamIndividualBirthDate                  = "BirthDate"
	FormParamIndividualCountry                    = "Country"
	FormParamIndividualDisplacementStatus         = "DisplacementStatus"
	FormParamIndividualEmail                      = "Email"
	FormParamIndividualFullName                   = "FullName"
	FormParamIndividualGender                     = "Gender"
	FormParamIndividualIsMinor                    = "IsMinor"
	FormParamIndividualMentalImpairment           = "MentalImpairment"
	FormParamIndividualPhoneNumber                = "PhoneNumber"
	FormParamIndividualPhysicalImpairment         = "PhysicalImpairment"
	FormParamIndividualPreferredName              = "PreferredName"
	FormParamIndividualPresentsProtectionConcerns = "PresentsProtectionConcerns"
	FormParamIndividualSensoryImpairment          = "SensoryImpairment"

	FormParamGetIndividualsEmail               = "email"
	FormParamGetIndividualsName                = "name"
	FormParamGetIndividualsPhoneNumber         = "phone_number"
	FormParamsGetIndividualsAddress            = "address"
	FormParamsGetIndividualsGender             = "gender"
	FormParamsGetIndividualsIsMinor            = "is_minor"
	FormParamsGetIndividualsProtectionConcerns = "presents_protection_concerns"
	FormParamsGetIndividualsAgeFrom            = "age_from"
	FormParamsGetIndividualsAgeTo              = "age_to"
	FormParamGetIndividualsCountryID           = "country_id"
	FormParamsGetIndividualsDisplacementStatus = "displacement_status"

	FileColumnIndividualID                         = "id"
	FileColumnIndividualAddress                    = "address"
	FileColumnIndividualBirthDate                  = "birth_date"
	FileColumnIndividualCountryID                  = "country_id"
	FileColumnIndividualDisplacementStatus         = "displacement_status"
	FileColumnIndividualEmail                      = "email"
	FileColumnIndividualFullName                   = "full_name"
	FileColumnIndividualGender                     = "gender"
	FileColumnIndividualIsMinor                    = "is_minor"
	FileColumnIndividualMentalImpairment           = "mental_impairment"
	FileColumnIndividualPhoneNumber                = "phone_number"
	FileColumnIndividualPhysicalImpairment         = "physical_impairment"
	FileColumnIndividualPreferredName              = "preferred_name"
	FileColumnIndividualPresentsProtectionConcerns = "presents_protection_concerns"
	FileColumnIndividualSensoryImpairment          = "sensory_impairment"
)
