package constants

const (
	FormParamIndividualAddress                    = "Address"
	FormParamIndividualBirthDate                  = "BirthDate"
	FormParamIndividualCountry                    = "Country"
	FormParamIndividualDisplacementStatus         = "DisplacementStatus"
	FormParamIndividualEmail                      = "Email"
	FormParamIndividualFullName                   = "FullName"
	FormParamIndividualGender                     = "Gender"
	FormParamIndividualIsMinor                    = "IsMinor"
	FormParamIndividualMentalImpairment           = "MentalImpairment"
	FormParamIndividualPhoneNumber                = "PhoneNumber"
	FormParamIndividualPhysicalImpairment         = "PhysicalImpairment"
	FormParamIndividualPreferredName              = "PreferredName"
	FormParamIndividualPresentsProtectionConcerns = "PresentsProtectionConcerns"
	FormParamIndividualSensoryImpairment          = "SensoryImpairment"

	FormParamGetIndividualsEmail               = "email"
	FormParamGetIndividualsName                = "name"
	FormParamGetIndividualsPhoneNumber         = "phone_number"
	FormParamsGetIndividualsAddress            = "address"
	FormParamsGetIndividualsGender             = "gender"
	FormParamsGetIndividualsIsMinor            = "is_minor"
	FormParamsGetIndividualsProtectionConcerns = "presents_protection_concerns"
	FormParamsGetIndividualsAgeFrom            = "age_from"
	FormParamsGetIndividualsAgeTo              = "age_to"
	FormParamGetIndividualsCountryID           = "country_id"
	FormParamsGetIndividualsDisplacementStatus = "displacement_status"

	FileHeaderIndividualID                         = "id"
	FileHeaderIndividualAddress                    = "address"
	FileHeaderIndividualBirthDate                  = "birth_date"
	FileHeaderIndividualCountryID                  = "country_id"
	FileHeaderIndividualDisplacementStatus         = "displacement_status"
	FileHeaderIndividualEmail                      = "email"
	FileHeaderIndividualFullName                   = "full_name"
	FileHeaderIndividualGender                     = "gender"
	FileHeaderIndividualIsMinor                    = "is_minor"
	FileHeaderIndividualMentalImpairment           = "mental_impairment"
	FileHeaderIndividualPhoneNumber                = "phone_number"
	FileHeaderIndividualPhysicalImpairment         = "physical_impairment"
	FileHeaderIndividualPreferredName              = "preferred_name"
	FileHeaderIndividualPresentsProtectionConcerns = "presents_protection_concerns"
	FileHeaderIndividualSensoryImpairment          = "sensory_impairment"
)
